# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'date')),
                ('a_value', models.FloatField(verbose_name=b'A Value')),
                ('b_value', models.FloatField(verbose_name=b'B Value')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Site')),
            ],
        ),
    ]
